# Run: golangci-lint run
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  modules-download-mode: vendor
  tests: true
  skip-dirs:
    - vendor
    - tools

linters:
  disable:
    - maligned
    - gci
    - exhaustivestruct
    - gomnd
  presets:
    - bugs
    - complexity
    - format
    - performance
    - style
    - unused

linters-settings:
  goimports:
    local-prefixes: prokrastintation-killer
  funlen:
    lines: 100
    statements: 40
  dogsled:
    max-blank-identifiers: 3
  cyclop:
    max-complexity: 20
govet:
  enable:
    - fieldalignment
